### ISSUE TITLE
"EmPOWER agent library" file(s) is missing from your github: empower-enb-agent.git

### ISSUE THREAD

**Issue by WindyCitySDR** [5g-empower/5g-empower.github.io#1]
Mr. Riggio,

Its a pretty cool project your working on, but per the instructions listed on your github website:

https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-the-VBS-empower-openairinterface

We can't complete the installation because this file is missing:

https://github.com/5g-empower/empower-enb-agent.git

Can you restore/upload it someplace so as to complete the installation please ?

**Comment by rriggio** [comment]
Done
