### ISSUE TITLE
Pre built WTP Firmwares is missing

### ISSUE THREAD

**Issue by nelcard** [5g-empower/5g-empower.github.io#2]
Mr. Riggio,

Thank you for this pretty cool project your working on.

I need your help with the next issue. I'm trying to download the Pre built WTP Firmwares for D-Link DIR 505A, but the links below are broken.

https://github.com/5g-empower/empower-openwrt-15.05/releases/download/20160714/openwrt-ar71xx-generic-dir-505-a1-squashfs-factory.bin

https://github.com/5g-empower/empower-openwrt-15.05/releases/download/20160714/openwrt-ar71xx-generic-dir-505-a1-squashfs-sysupgrade.bin

Can you please tell me if the files are in others links?

Thanks in advance for your support.

**Comment by WindyCitySDR** [comment]
nelcard,


Here are the files your looking for:

[https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/openwrt-ar71xx-generic-dir-505-a1-squashfs-factory.bin](url)

[https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/openwrt-ar71xx-generic-dir-505-a1-squashfs-sysupgrade.bin](url)

If these are the correct files, please update us, then mark this resolved and close this "Issue" out.

**Comment by rriggio** [comment]
I will uploaded the new firmwares asap.

**Comment by nelcard** [comment]
Thank you for your quick response.

I understand that the Pre built WTP Firmwares include the Empower agent (with router Click) and OpenVSwitch already installed.

The files that you suggest above are from openwrt site. In that case, Do I have to install the empower agent and OpenVswitch by myself?

Tell me please if I'm correct.

Thanks in advance.

-- 
nelcard

**Comment by WindyCitySDR** [comment]
nelcard,

> The files that you suggest above are from openwrt site. In that case, Do I have to install the empower agent and OpenVswitch by myself? >

Yes I stand corrected.  Until Riggio uploads the firmware with all that included, you will have to install the empower agent and OpenVswitch yourself.

**Comment by rriggio** [comment]
The easiest way is to follow this:

https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-the-WTP

then you can build the images for any platform supported by OpenWRT. However I have already uploaded the new firmware for the ALIX board. I will soon upload the others.

**Comment by nelcard** [comment]
Thanks a lot for your kind and quick support.

I'm gonna close the "issue".

--

nelcard

**Comment by nelcard** [comment]
resolved
