### ISSUE TITLE
CPP Configuration

### ISSUE THREAD

**Issue by nMaroulis** [5g-empower/5g-empower.github.io#4]
We're trying to set the CPPs. We want to use Soekris 5501 as the CPP device. What device do you use as CPP? If you use Soekris, how did you install Debian on it, with a CF Card?
Thank you in advance

**Comment by rriggio** [comment]
You can boot from the USB stick and install to an hard disk (e.g. an SSD) or you can also install to another USB stick. We installed debian on another USB stick so we can easily swap the OS.
