### ISSUE TITLE
Lvap Agent on Ubuntu

### ISSUE THREAD

**Issue by nMaroulis** [5g-empower/5g-empower.github.io#5]
Hello,
Is there any way to run the lvap-agent on a PC with Ubuntu? So basically the PC implements a WTP.

**Comment by rriggio** [comment]
Hi,

in principle yes. However you need a patched kernel to run it. I can point
you to the patch but
then you need to adapt it to the kernel version you are using.

R.

**Comment by nMaroulis** [comment]
Yes I'd like that, anything that helps is welcome.
Thank you in advance

**Comment by rriggio** [comment]
The most important patch is this:

https://github.com/5g-empower/empower-openwrt-15.05/blob/chaos_calmer/package/kernel/mac80211/patches/905-ath9k-bssid-mask.patch

One big notice, this works only for the ath9k driver so for 11n atheros
cards. If you have a different card the amount
of work is quite higher since you have to understand how to configure the
BSSID mask of that card.

R.

**Comment by nMaroulis** [comment]
I'm using the ath9k driver so that's fine. With the code provided, do I copy/paste it in a file that already exists or do I create a file with this code somewhere? Also there are 3 configuration files on the wiki (empower/wireless/network), where do I copy/paste these configurations ? (/etc/network/interfaces ??)

**Comment by rriggio** [comment]
Hi,

well you need to apply the patch to the linux kernel. So I assume you have
to download the linux kernel
sources matching the kernel running in your ubuntu box, and apply the patch
to the ath9k driver.

The other three files are openwrt specific. The wireless file can be
replaced by some commands to
create a monitor interface. However the hardest part is to patch the ath9k
driver.

R.

**Comment by Giwrgosyea** [comment]
According to that , instead of patching new kernel can I run the empower OPENWRT on a VM ?
The machine which is running the VM, supports 11n atheros cards.

**Comment by rriggio** [comment]
Not sure. The host OS should expose the raw interface to the VM. I never
done that. But I would be very interested in\
knowing if that could work.

**Comment by Giwrgosyea** [comment]
I will share  with you the VM configurations if it  works properly. 
But ifconfig -a does not report any  empower0  and monitor0 interface should I add any configurations or add the interfaces to the machine before starting the VM ?

**Comment by rriggio** [comment]
That is why I am a bit skeptic about this VM thing. The point is that the
host system
should expose to the VM the raw interface, this is the one visible with the
command

iw phy list

not sure of the syntx.

**Comment by Giwrgosyea** [comment]
I finally managed to patch ath9k.patch you suggested above.

Any suggestion on how can I adapt your WTP configuration files?

**Comment by rriggio** [comment]
Hi, good job. The relevant file for you is this:

https://github.com/5g-empower/empower-openwrt-packages-15.05/blob/master/empower-lvap-agent/files/empower_config.sh

Before running this you need to create a monitor interface using the "iw" command:

iw phy phy0 interface add moni0 type monitor

Then you need to install OpenVSwitch. You will also need to have on the machine running everything a dhcp server (e.g. dnsmasq). In alternative you can bridge the wired interface of the laptop with the OVS bridge. In this way if you connect the laptop to a LAN with a DHCP that DHCP will also serve the wifi clients.

The empower_config file has the following syntax:

empower_config.sh -o <BRIDGE> -a <MASTER_IP> -p <MASTER_PORT> -i <IFNAMES> -f <DEBUGFS> -v <VIRTUAL_IFNAME> 

BRIDGE is the name of the OVS bridge
MASTER IP and PORT are the IP and PORT of the machine where the empower-runtime is running.
IFNAMES is the list of monitor interfaces in your case "moni0"
DEBUGFS is the part to the new file created by your patch in the debugfs filesystem, try to search your filesystem loking for a file names bssid_mask
VIRTUAL_IFNAME is the name of the tun interface that must be created by click, put empower0

After executing this script you will get as output a click configuration. You can then run this configuration with click:

click empower.click

If everything goes well then click should start.

From another shell you should add the empower0 interface to the OVS bridge. 

This should be all. The laptop should now run like an AP and should connect to the runtime.

**Comment by Giwrgosyea** [comment]
after running the script I get a click file as screen output  and 
./empower_config.sh: 81: [: unexpected operator
./empower_config.sh: 127: [: Illegal number: 
./empower_config.sh: 133: [: unexpected operator

**Comment by rriggio** [comment]
Could you please copy here how you call the script? I will try to run it on
my machine.

R.

**Comment by Giwrgosyea** [comment]
Exactly as you suggest above.
./empower_config.sh -o br0 -a XX.XX.XX.XX -p 8888 -i moni0 -f /sys/kernel/debug/ieee80211/phy0/ath9k/bssid_extra -v empower0

**Comment by rriggio** [comment]
Hi,

it is the path of the iw command. In the script I have that hardcoded. On
openwrt is:

/usr/sbin/iw

while on my fedora is

/sbin/iw

Try to change that by hand. I will make the script more generic in the next
release.

For example try to define a variable like this:

IW=$(which iw)

and try to use this across the script. If it works I will merge that in the
github.

R.

**Comment by Giwrgosyea** [comment]
My mistake not mention it , i already fix this with my machine path to iw before reply to you my output. So changing iw path does not fix the problem.

**Comment by rriggio** [comment]
Try this:

./empower_config.sh -o br0 -a XX.XX.XX.XX -p 8888 -i "moni0" -f
"/sys/kernel/debug/ieee80211/phy0/ath9k/bssid_extra" -v empower0

notice the quotes (").

Just to make sure. Is the moni0 created and up?

R.
