### ISSUE TITLE
No connection between VBS and Controller

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/5g-empower.github.io#6]
Hello.
 we followed the instructions for setting up the VBS from the wiki pages ("https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-the-Controller and https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-the-VBS") but we were unable to connect to the Empower Controller. We build the latest empower oai openairinterface5g following the instrunctions from the vanilla's wiki and it seems that everything compiles and runs normally. Thats why we would like to ask you, if there is anything we need to run in addition to the lte_softmodem, and if it is possible to send us a document with the services exposed from VBS.

**Comment by herlesupreeth** [comment]
Apologies for the late reply, could you please share with us the configuration file and the Empower controller GUI screenshot of all the tabs. Also, the eNB configuration file.

**Comment by Giwrgosyea** [comment]
Problem resolved.
