### ISSUE TITLE
Problem with Lvnf Creation and Spawning

### ISSUE THREAD

**Issue by nMaroulis** [5g-empower/5g-empower.github.io#7]
Hi,
I'm trying to create an lvnf but i fail to do so. I followed your instructions in the wiki and i have some issues. First of all the image is created normally with no problem. In lvnf=LVNF(img) i get the error that there are too few arguments for the LVNF init, so I try lvnf=LVNF(None,self.tenant_id,img,None) and it runs normally. Next I assign the cpp with lvnf.cpp = cpp (cpp is an iterator of self.cpps()), this also works. My problems are that no LVNFs are created and that lvnf.ports[0] doesn't work and crash the application. Any suggestions? Thank you.

**Comment by rriggio** [comment]
I have made a few corrections to the wiki and added a full example.

R.

**Comment by nMaroulis** [comment]
Thank you, everything works fine now. Is there any guide on how to write a click script that you could provide?

**Comment by nMaroulis** [comment]
Hi,
I'm more interested in flow redirection and manipulation by the LVNFs, but in order to get started I'd like to learn how to write a click script a little better. I'll wait for updates in your Wiki.
Thank you

**Comment by rriggio** [comment]
Hi Nikos,

I have updated the LVNF documentation. Please check the new tutorial on
SFC. It is very simple and minimalistic but should give you an idea of what
can be achieved.

R.
