### ISSUE TITLE
Client cant connect to Wifi

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/5g-empower.github.io#8]
Client's mac address is added on allowed section on controller , tenants have been created , wtps are added on tenants , everyhing seems to work fine.
But empower(tenant) network is not availabe for the clients. 
Should I add wlan0 to br-ovs on the wtps? any clue ?

**Comment by rriggio** [comment]
Could you copy&paste the log on the controller? With so little information it is hard to understand where is the problem. If you followed precisely the instructions on the wiki everything should work without any other configuration on the wtp.

Btw what is wlan0? there should be no wlan0 interface on the wtp if you followed our instructions.

**Comment by Giwrgosyea** [comment]
Controller logs seems to be fine as well as wtp's logs. I followed your instructions but instead of flashing ext4.img , we installed x86-64 rootfs image . So the problem is that the clients can not find bar or foo slice to connect. 
Its seems odd that after installing x86-64 roots image ifconfig -a reports wlan0 interface .

**Comment by rriggio** [comment]
flash the image specified in the wiki and try again.

**Comment by Giwrgosyea** [comment]
Image seems to be fine , WTP connects with the controller and  receives/sends probe request as well as receiving rates. The LVAPs are available on controller and seems to be connected with the WTP. I can use also the WTP as AP using the radio interface on /config/wireless but after connecting them to the AP,  no IP is assigned on the LVAPs. Bssid_extra file is there and lsmod report that ath9k is loaded.
So the only problem is that allowed clients cant access the slice.
I tried to change the channel and the frequency of the WTP but still the slice is unavailable for the clients.

Logs from controller after trying to connect allowed client:
INFO:lvapp.lvappconnection:Probe request from 7C:C3:A1:A8:0B:BC ssid Broadcast
INFO:lvapp.lvappconnection:Spawning new LVAP 7C:C3:A1:A8:0B:BC on 5A:80:FA:8C:FB:41
INFO:lvapp.lvappconnection:Add lvap addr 7C:C3:A1:A8:0B:BC net_bssid 02:CA:FE:A8:0B:BC lvap_bssid 02:CA:FE:A8:0B:BC ssid None ssids [ bar ] assoc_id 0
INFO:lvapp.lvappconnection:Set tx policy 7C:C3:A1:A8:0B:BC no_ack False rts_cts 2436 mcast legacy mcs 1.0, 2.0, 36.0, 6.0, 9.0, 11.0, 12.0, 48.0, 18.0, 54.0, 24.0 ht_mcs  ur_count 3
INFO:intentserver:Intent POST /intent/poa:
{
    "version": "1.0",
    "dpid": "5A:80:FA:8C:FB:41",
    "port": 1,
    "hwaddr": "7C:C3:A1:A8:0B:BC"
}
WARNING:intentserver:Intent interface not found
INFO:lvapp.lvappconnection:Sending probe response to 7C:C3:A1:A8:0B:BC



Logs on WTP after trying to connect with client:
ebs :: EmpowerBeaconSource :: push :: sending probe request to ctrl 7C-C3-A1-A8-0B-BC
el :: EmpowerLVAPManager :: handle_add_lvap :: invalid ssids size (1)
el :: EmpowerLVAPManager :: handle_probe_response :: sta 7C:C3:A1:A8:0B:BC
el :: EmpowerLVAPManager :: handle_probe_response :: unknown LVAP 7C:C3:A1:A8:0B:BC ignoring
ebs :: EmpowerBeaconSource :: push :: Ignored element id 3 1
ebs :: EmpowerBeaconSource :: push :: ProbeReq: 7C-C3-A1-A8-0B-BC ssid Broadcast rates { 2 4 11 22 12 18 24 36 } 48 72 96 108 HT_CAPS [ LDPC 20/40MHz PS_DISABLED SGI20 SGI40 TX_STBC RX_STBC_1 A-MSDU Length: 3839 DSSS_CCK_40MHz RX A-MPDU Length: 65535 MPDU Density: 8us SUPPORTED MCSes { 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 } Rx Highest TP: 0 TX 3SS ]
ebs :: EmpowerBeaconSource :: push :: sending probe request to ctrl 7C-C3-A1-A8-0B-BC

**Comment by rriggio** [comment]
The error on the invalid ssid size makes me think that this is a problem of
non-aligned version of agent and controller.

Can you do a git pull on both agent and runtime?
