### ISSUE TITLE
Unable to start empower WTP agent on openwrt

### ISSUE THREAD

**Issue by rohankharade** [5g-empower/5g-empower.github.io#9]
I have cross compiled image with empower lvap agent for Mikrotik RB 433AH. Also [configured network ](https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-the-WTP) settings. I am unable to start empower WTP agent.

`root@OpenWrt:/etc/config# /etc/init.d/empower restart
ovs-vsctl: no port named empower0
/tmp/empower.click:1: syntax error near ':'
/tmp/empower.click:1: syntax error near '/'
/tmp/empower.click:1: syntax error near '.'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error: expected port number
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near ']'
root@OpenWrt:/etc/config# 

`

**Comment by rriggio** [comment]
cat you provide the content of the /etc/config/wireless file and the output
of ifconfig? Do you see a process name click running?

**Comment by rohankharade** [comment]
Hii

No click process is running, only OVS process seems to be running
Please find my config files 

/etc/config/network
`
 config interface 'loopback'  
     option ifname 'lo'  
     option proto 'static'  
     option ipaddr '127.0.0.1'  
     option netmask '255.0.0.0'  

 config device  
     option name 'br-ovs'  
     option type 'ovs'  
     list ifname 'eth0'  

 config interface 'wan'  
     option ifname 'br-ovs'  
     option proto 'dhcp'  

 config interface lan  
     option ifname   eth1  
     option proto    static  
     option ipaddr   192.168.250.1  
     option netmask  255.255.255.0  
`

/etc/config/wireless
`config wifi-device  radio0
        option type     mac80211
        option channel  36
        option hwmode   11a
        option path     'pci0000:00/0000:00:0c.0'

config wifi-iface empower0
        option device   radio0
        option mode     monitor
        option ifname   moni0`

/etc/config/empower
config empower general
    option "master_ip" "192.168.0.9"
    option "master_port" "4433"
    option "network" "wan"
    option "interface" "empower0"
    list "ifname" "empower0"

ifconfig
br-ovs    Link encap:Ethernet  HWaddr D4:CA:6D:FE:DD:3A                         
          inet6 addr: fe80::d6ca:6dff:fefe:dd3a/64 Scope:Link                   
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1                    
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0                    
          TX packets:12 errors:0 dropped:0 overruns:0 carrier:0                 
          collisions:0 txqueuelen:0                                             
          RX bytes:0 (0.0 B)  TX bytes:2448 (2.3 KiB)                           
                                                                                
eth0      Link encap:Ethernet  HWaddr D4:CA:6D:FE:DD:3A                         
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1                    
          RX packets:377 errors:0 dropped:0 overruns:0 frame:0                  
          TX packets:2048 errors:0 dropped:0 overruns:0 carrier:0               
          collisions:0 txqueuelen:1000                                          
          RX bytes:30533 (29.8 KiB)  TX bytes:648112 (632.9 KiB)                
          Interrupt:5                                                           
                                                                                
eth1      Link encap:Ethernet  HWaddr D4:CA:6D:FE:DD:3B                         
          inet addr:192.168.250.1  Bcast:192.168.250.255  Mask:255.255.255.0    
          inet6 addr: fe80::d6ca:6dff:fefe:dd3b/64 Scope:Link                   
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1                    
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0                    
          TX packets:140 errors:0 dropped:0 overruns:0 carrier:0                
          collisions:0 txqueuelen:1000                                          
          RX bytes:0 (0.0 B)  TX bytes:12440 (12.1 KiB)                         
          Interrupt:4                                                           
                                                                                
lo        Link encap:Local Loopback                                             
          inet addr:127.0.0.1  Mask:255.0.0.0                                   
          inet6 addr: ::1/128 Scope:Host                                        
          UP LOOPBACK RUNNING  MTU:65536  Metric:1                              
          RX packets:7987 errors:0 dropped:0 overruns:0 frame:0                 
          TX packets:7987 errors:0 dropped:0 overruns:0 carrier:0               
          collisions:0 txqueuelen:0                                             
          RX bytes:543396 (530.6 KiB)  TX bytes:543396 (530.6 KiB)              
                                                                                
root@OpenWrt:/etc/config# 
root@OpenWrt:~# ovs-vsctl show
55133330-7aac-4a3c-8bee-b54d59e473cd
    Bridge br-ovs
        Port "eth0"
            Interface "eth0"
        Port br-ovs
            Interface br-ovs
                type: internal
root@OpenWrt:~#

**Comment by rriggio** [comment]
the moni0 interface is not visible in ifconfig. you need to debug why it is
not created. Maybe the driver is not loaded. Which wifi card are you using?

**Comment by rohankharade** [comment]
My wlan PCI number was wrong. Fixed the same. Click is running as background process.

**root@OpenWrt:/etc/config# /etc/init.d/empower restart**
ovs-vsctl: no port named empower0
[  993.740000] device empower0 entered promiscuous mode
root@OpenWrt:/etc/config# 

**root@OpenWrt:/etc/config# ovs-vsctl show**
027e8f9d-d53f-4a43-8704-565e72534476
    Bridge br-ovs
        Controller "tcp:192.168.0.9:6633"
        Port br-ovs
            Interface br-ovs
                type: internal
        Port "eth0"
            Interface "eth0"
        Port "empower0"
            Interface "empower0"
**root@OpenWrt:/etc/config#  logread**
Thu Jul 27 12:29:12 2017 user.notice empower: Checking interface empower0.
Thu Jul 27 12:29:12 2017 user.notice empower: Interface moni0 found.
Thu Jul 27 12:29:14 2017 user.notice empower: Setting moni0 MTU to 2300.
Thu Jul 27 12:29:14 2017 user.notice empower: Setting moni0 channel to 11.
Thu Jul 27 12:29:14 2017 user.notice empower: Bringing moni0 up.
Thu Jul 27 12:29:14 2017 user.notice empower: ip: 192.168.0.9
Thu Jul 27 12:29:14 2017 user.notice empower: port: **4433**
Thu Jul 27 12:29:14 2017 user.notice empower: ifnames:  moni0
Thu Jul 27 12:29:14 2017 user.notice empower: debugfs:  /sys/kernel/debug/ieee80211/phy0/netdev:moni0/../ath9k/bssid_extra
Thu Jul 27 12:29:14 2017 user.notice empower: virtual: empower0
Thu Jul 27 12:11:34 2017 kern.info kernel: [ 1800.630000] device empower0 entered promiscuous mode
Thu Jul 27 12:11:38 2017 daemon.notice ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl add-port br-ovs empower0
Thu Jul 27 12:11:38 2017 daemon.notice ovs-vswitchd: ovs|00164|bridge|INFO|bridge br-ovs: added interface empower0 on port 5
Thu Jul 27 12:11:38 2017 daemon.notice ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl set-controller br-ovs tcp:192.168.0.9:**6633**
Thu Jul 27 12:11:42 2017 daemon.warn ovs-vswitchd: ovs|00165|rconn|WARN|br-ovs<-tcp:192.168.0.9:**6633**: connection dropped (Connection refused)
Thu Jul 27 12:11:50 2017 daemon.warn ovs-vswitchd: ovs|00166|rconn|WARN|br-ovs<-tcp:192.168.0.9:**6633**: connection dropped (Connection refused)



**Now getting connection issue on Empower controller** 
**~/empower5G/empower-runtime$ ./empower-runtime.py**
INFO:tornado.access:200 GET /api/v1/components?_=1501233274579 (127.0.0.1) 0.63ms
INFO:core.pnfpserver:Incoming connection from ('192.168.0.11', 52676)
ERROR:lvapp.lvappconnection:Unknown WTP (D4:CA:6D:FE:DD:3A), closing connection
INFO:tornado.access:200 GET /api/v1/tenants?_=1501233274581 (127.0.0.1) 0.88ms

Though we are giving port 4433 for empower, ovs using 6633 (OF) port for controller connection. 
So does openflow controller Ryu is required for single WTP connection ?

**Comment by rriggio** [comment]
Ryu is not needed for a single or even multiple WTPs. Check the following
wiki pages:

https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-the-EmPOWER-Controller
https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-a-Network-Slice

**Comment by rohankharade** [comment]
Hi Roberto

Now I tried 'AP' mode instead of 'monitor' mode. Click is unable to start by then.

**root@OpenWrt:/etc/config# /etc/init.d/empower restart**
ovs-vsctl: no port named empower0
/tmp/empower.click:1: syntax error near ':'
/tmp/empower.click:1: syntax error near '/'
/tmp/empower.click:1: syntax error near '.'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near '<'
/tmp/empower.click:1: syntax error near '>'
/tmp/empower.click:1: syntax error: expected port number
/tmp/empower.click:1: syntax error near '-'
/tmp/empower.click:1: syntax error near ']'

**root@OpenWrt:/etc/config# lograed**
ed Aug  2 09:50:53 2017 user.notice empower: Stopping...
Wed Aug  2 09:50:53 2017 daemon.notice ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl del-port br-ovs empower0
Wed Aug  2 09:50:53 2017 daemon.err ovs-vsctl: ovs|00002|vsctl|ERR|no port named empower0
Wed Aug  2 09:50:53 2017 daemon.warn ovs-vswitchd: ovs|01335|netlink_notifier|WARN|received bad netlink message
Wed Aug  2 09:50:53 2017 user.notice empower: Checking interface empower0.
Wed Aug  2 09:50:53 2017 user.notice empower: Device moni0 not monitor mode. Ignoring.
Wed Aug  2 09:50:53 2017 user.notice empower: ip: 192.168.0.9
Wed Aug  2 09:50:53 2017 user.notice empower: port: 4433
Wed Aug  2 09:50:53 2017 user.notice empower: ifnames: 
Wed Aug  2 09:50:53 2017 user.notice empower: debugfs: 
Wed Aug  2 09:50:53 2017 user.notice empower: virtual: empower0
Wed Aug  2 09:50:55 2017 user.notice empower: Unable to start click. Check logs.

**Comment by rriggio** [comment]
empower works on monitor interfaces, so it is normal that it does not work
in monitor mode.

R.

**Comment by rohankharade** [comment]
thanks for prompt reply,

It works well for Minitor mode. Will you please inform which part of code I should take a look to make it work in AP mode.

thanks

**Comment by rriggio** [comment]
It cannot work in ap mode. The agent running on the AP is implementing the
actual wifi access point. This is
needed in order to enable control from the controller. Why do you want to
run it in ap mode?

R.

**Comment by rohankharade** [comment]
I want to connect wireless stations to the AP which can not be connected in monitor mode. As you said lvap agent on AP does the same, my doubt is how single radio can work in both monitor and AP mode ?

**Comment by rriggio** [comment]
Did you follow the following tutorial:

https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-the-EmPOWER-Controller
https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-a-Network-Slice

After doing so you will be able to attach a standard client to the network.

R.

**Comment by rohankharade** [comment]
yes 

I followed the same. I will try it once again properly.

thanks
